# Generated by Django 3.2.3 on 2021-10-27 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Easy-paced run, Strength training,...', max_length=50, unique=True, verbose_name='Name of the workout type')),
            ],
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Please use the following format: <em>YYYY-MM-DD</em>.')),
                ('time', models.TimeField(blank=True)),
                ('name', models.CharField(blank=True, max_length=1000)),
                ('description', models.CharField(blank=True, max_length=1000)),
                ('feeling', models.CharField(blank=True, choices=[('GREAT', 'Great'), ('GOOD', 'Good'), ('NORMAL', 'Normal'), ('POOR', 'Poor'), ('TERRIBLE', 'Terrible')], max_length=10)),
                ('effort', models.IntegerField(blank=True, choices=[(0, 'None'), (1, 'Moderate'), (10, 'Maxeffort')])),
                ('notes', models.CharField(blank=True, max_length=1000, verbose_name='post workout notes')),
                ('workouttype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='log.workouttype')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
