# Generated by Django 3.2.3 on 2021-10-27 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workouttype',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='workout',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
