# Generated by Django 3.2.3 on 2021-10-27 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0002_auto_20211027_1433'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout',
            name='time',
        ),
    ]
