# Generated by Django 3.2.3 on 2021-10-27 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0003_remove_workout_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
