# Generated by Django 3.2.3 on 2021-10-27 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0004_workout_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='effort',
            field=models.IntegerField(blank=True, choices=[(0, 'None'), (1, 'Moderate'), (10, 'Maxeffort')], default=None),
        ),
    ]
