# Generated by Django 3.2.3 on 2021-10-27 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0007_alter_workout_effort'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='effort',
            field=models.IntegerField(blank=True, choices=[('1', 'None'), ('2', 'Very light'), ('NORMAL', 'Normal'), ('POOR', 'Poor'), ('TERRIBLE', 'Terrible')]),
        ),
    ]
