# Generated by Django 3.2.3 on 2021-10-27 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0008_alter_workout_effort'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='effort',
            field=models.CharField(blank=True, choices=[('1', 'None'), ('2', 'Very light'), ('NORMAL', 'Normal'), ('POOR', 'Poor'), ('TERRIBLE', 'Terrible')], max_length=20),
        ),
        migrations.AlterField(
            model_name='workout',
            name='feeling',
            field=models.CharField(blank=True, choices=[('GREAT', 'Great'), ('GOOD', 'Good'), ('NORMAL', 'Normal'), ('POOR', 'Poor'), ('TERRIBLE', 'Terrible')], max_length=20),
        ),
    ]
