# Generated by Django 3.2.3 on 2021-10-27 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0010_alter_workout_effort'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='effort',
            field=models.CharField(blank=True, choices=[('1', 'Very light'), ('2', 'Light'), ('3', 'Light'), ('4', 'Moderate'), ('5', 'Moderate'), ('6', 'Moderate'), ('7', 'Hard'), ('8', 'Hard'), ('9', 'Very hard'), ('10', 'Max effort')], max_length=20),
        ),
    ]
